### ISSUE TITLE
add_loopback_full.py lxml.etree.XMLSyntaxError

### ISSUE THREAD

**Issue by foehn2002** [DevNetSandbox/sbx_nxos_ao#2]
When execute add_loopback_full.py

Traceback (most recent call last):
  File "./add_loopback_full.py", line 99, in <module>
    sys.exit(main())
  File "./add_loopback_full.py", line 93, in main
    netconf_response = m.edit_config(target='running', config=new_ip)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/edit.py", line 65, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "/usr/local/lib/python3.6/dist-packages/ncclient/xml_.py", line 145, in validated_element
    ele = to_ele(x)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 7
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: adminSt line 7 and up, line 7, column 33

Code: 
<adminSt>up</UP>
should be 
<adminSt>up</adminSt>

**Comment by foehn2002** [comment]
`<adminSt>up</up>` 
should be
`<adminSt>up</adminSt>`
